[package]
name = "rrcm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.11", features = ["derive"] }
dirs = "5.0.1"
itertools = "0.11.0"
path_abs = "0.5.1"
termion = "2.0.1"
trash = "3.0.6"

[targets.'cfg(windows)'.dependencies]
dunce = "1.0.3"
