[package]
name = "rrcm"
version = "0.2.3"
edition = "2021"
license = "MIT"
description = "Rust RC file Management commands"
repository = "https://github.com/mizuki0629/rrcm"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.11", features = ["derive"] }
dirs = "5.0.1"
itertools = "0.11.0"
path_abs = "0.5.1"
trash = "3.0.6"
dunce = "1.0.3"
confy = { version = "0.5.1" }
serde = { version = "1.0", features = ["derive"] }
maplit = "1.0.2"
dirs-sys = "0.4.1"
crossterm = "0.26.1"
