[target.armv7-unknown-linux-gnueabihf]
dockerfile = "Dockerfile"

[target.armv7-unknown-linux-musleabihf]
dockerfile = "Dockerfile"

[target.aarch64-unknown-linux-gnu]
dockerfile = "Dockerfile"

[target.aarch64-unknown-linux-musl]
dockerfile = "Dockerfile"
