[config]
skip_core_tasks = true

[env]
NEXTEST_FILTER  = { source = "${CARGO_MAKE_RUST_TARGET_OS}", default_value = "all()", mapping = {"windows" = "not test(/win_need_admin/)" } }

[tasks.build]
description = "Build project."
command = "cargo"
args = ["build"]

[tasks.clean]
description = "Clean target directory."
command = "cargo"
args = ["clean"]

[tasks.set-nextest-filter-all]
env = { NEXTEST_FILTER = "all()" }

[tasks.test-all]
dependencies = [ "set-nextest-filter-all" ]
run_task = { name = "test" }

[tasks.test]
install_crate = "cargo-nextest"
command = "cargo"
args = ["nextest", "run", "-E", "${NEXTEST_FILTER}"]

[tasks.readme]
description = "Generate README.md"
install_crate = "cargo-readme"
command = "cargo"
args = ["readme", "--no-indent-headings", "--no-license", "--no-title", "-i", "src/main.rs", "-o", "README.md"]
category = "Documentation"

[tasks.docs-flow]
description = "Generate rust documentation."
category = "Documentation"
dependencies = [
    "pre-docs",
    "docs",
    "post-docs",
    "readme",
]

[tasks.install-cargo-nextest]
install_crate = { crate_name = "cargo-nextest", binary = "cargo", test_arg = ["nextest", "--help"] }

[tasks.install-cargo-llvm-cov]
install_crate = { crate_name = "cargo-llvm-cov", binary = "cargo", test_arg = ["llvm-cov", "--help"] }

[tasks.llvm-cov-dev]
description = "Generate code coverage report."
category = "Test"
command = "cargo"
args = ["llvm-cov", "nextest", "-E", "${NEXTEST_FILTER}"]

[tasks.llvm-cov-ci]
description = "Generate code coverage report."
category = "Test"
dependencies = [ "set-nextest-filter-all" ]
command = "cargo"
args = ["llvm-cov", "nextest", "--all-features", "--workspace", "--codecov", "--output-path", "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/codecov.json", "-E", "${NEXTEST_FILTER}"]

[tasks.llvm-cov]
description = "Generate code coverage report."
category = "Test"
dependencies = ["install-cargo-llvm-cov", "install-cargo-nextest"]
run_task = [
    { name = "llvm-cov-ci", condition = { env_true = [ "CARGO_MAKE_CI" ] }},
    { name = "llvm-cov-dev" },
]


[tasks.coverage-all]
dependencies = [ "set-nextest-filter-all" ]
run_task = { name = "coverage" }

[tasks.coverage]
description = "Generate code coverage report."
category = "Test"
run_task = { name = "llvm-cov" }

[tasks.echo]
command = "echo"
args = ["${CARGO_MAKE_CI}", "${CARGO_MAKE_PR}", "${CARGO_MAKE_CI_BRANCH_NAME}", "${CARGO_MAKE_CI_VENDOR}"]

[tasks.audit]
description = "Audit dependencies for security vulnerabilities."
category = "Test"
command = "cargo"
args = ["audit"]
install_crate = "cargo-audit"
