name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Crate
      uses: actions/checkout@v3
    - name: Set Toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: rustfmt, clippy, llvm-tools-preview
    - uses: Swatinem/rust-cache@v2
    - name: Run check
      run: cargo check
    - name: Run rustfmt
      run: cargo fmt --all -- --check
    - name: Run clippy
      run: cargo clippy -- -D warnings
    - uses: taiki-e/install-action@cargo-llvm-cov
    - uses: taiki-e/install-action@cargo-nextest
    - uses: taiki-e/install-action@cargo-make
    - name: Generate code coverage
      run: cargo make coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: target/codecov.json
        fail_ci_if_error: true


  test:
    name: build ${{ matrix.job.target }}
    permissions:
      contents: write
    runs-on: ${{ matrix.job.os }}
    needs: [update_release_draft]
    strategy:
      fail-fast: false
      matrix:
        job:
          - { os: ubuntu-latest  , target: x86_64-unknown-linux-gnu       , test: "test"       }
          - { os: ubuntu-latest  , target: x86_64-unknown-linux-musl      , test: "test-cross" }
          - { os: ubuntu-latest  , target: armv7-unknown-linux-gnueabihf  , test: "test-cross" }
          - { os: ubuntu-latest  , target: armv7-unknown-linux-musleabihf , test: "test-cross" }
          - { os: ubuntu-latest  , target: aarch64-unknown-linux-gnu      , test: "test-cross" }
          - { os: ubuntu-latest  , target: aarch64-unknown-linux-musl     , test: "test-cross" }
          - { os: macos-latest   , target: x86_64-apple-darwin            , test: "test"       }
          - { os: macos-latest   , target: aarch64-apple-darwin           , test: "test"       }
          - { os: windows-latest , target: x86_64-pc-windows-msvc         , test: "test"       }
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          
      - name: Rust Cache 
        uses: Swatinem/rust-cache@v2

      - name: Install cross
        uses: taiki-e/install-action@cross

      - name: Install cargo-make
        uses: taiki-e/install-action@cargo-make

      - name: Test
        run: cargo make ${{ matrix.job.test }} --target ${{ matrix.job.target }}
